//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ESFA.DC.ReferenceData.FCS.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:sfa:schemas:contract", IsNullable=false)]
    public partial class contract : contractType {
        
        private decimal schemaVersionField;
        
        public contract() {
            this.schemaVersionField = ((decimal)(11.00m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal schemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class contractType {
        
        private contractType[] contractsField;
        
        private fundingType fundingTypeField;
        
        private period periodField;
        
        private fundingStream fundingStreamField;
        
        private contractAllocationsContractAllocation[] contractAllocationsField;
        
        private string contractNumberField;
        
        private int contractVersionNumberField;
        
        private int contractSubVersionNumberField;
        
        private bool contractSubVersionNumberFieldSpecified;
        
        private TerminationContractAttrsCT terminationContractAttrsField;
        
        private System.Nullable<System.DateTime> contractApprovalDateField;
        
        private bool contractApprovalDateFieldSpecified;
        
        private System.Nullable<System.DateTime> statusLastUpdatedDateField;
        
        private bool statusLastUpdatedDateFieldSpecified;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private bool lastModifiedDateFieldSpecified;
        
        private string descriptionField;
        
        private contractor contractorField;
        
        private hierarchyType hierarchyTypeField;
        
        private string contractType1Field;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private contractStatusType contractStatusField;
        
        private System.Nullable<decimal> contractValueField;
        
        private bool contractValueFieldSpecified;
        
        private string parentContractNumberField;
        
        private System.Nullable<int> parentContractVersionNumberField;
        
        private bool parentContractVersionNumberFieldSpecified;
        
        private string amendmentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contract", IsNullable=false)]
        public contractType[] contracts {
            get {
                return this.contractsField;
            }
            set {
                this.contractsField = value;
            }
        }
        
        /// <remarks/>
        public fundingType fundingType {
            get {
                return this.fundingTypeField;
            }
            set {
                this.fundingTypeField = value;
            }
        }
        
        /// <remarks/>
        public period period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        public fundingStream fundingStream {
            get {
                return this.fundingStreamField;
            }
            set {
                this.fundingStreamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contractAllocation", IsNullable=false)]
        public contractAllocationsContractAllocation[] contractAllocations {
            get {
                return this.contractAllocationsField;
            }
            set {
                this.contractAllocationsField = value;
            }
        }
        
        /// <remarks/>
        public string contractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        public int contractVersionNumber {
            get {
                return this.contractVersionNumberField;
            }
            set {
                this.contractVersionNumberField = value;
            }
        }
        
        /// <remarks/>
        public int contractSubVersionNumber {
            get {
                return this.contractSubVersionNumberField;
            }
            set {
                this.contractSubVersionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractSubVersionNumberSpecified {
            get {
                return this.contractSubVersionNumberFieldSpecified;
            }
            set {
                this.contractSubVersionNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TerminationContractAttrsCT TerminationContractAttrs {
            get {
                return this.terminationContractAttrsField;
            }
            set {
                this.terminationContractAttrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> ContractApprovalDate {
            get {
                return this.contractApprovalDateField;
            }
            set {
                this.contractApprovalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContractApprovalDateSpecified {
            get {
                return this.contractApprovalDateFieldSpecified;
            }
            set {
                this.contractApprovalDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> StatusLastUpdatedDate {
            get {
                return this.statusLastUpdatedDateField;
            }
            set {
                this.statusLastUpdatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusLastUpdatedDateSpecified {
            get {
                return this.statusLastUpdatedDateFieldSpecified;
            }
            set {
                this.statusLastUpdatedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastModifiedDateSpecified {
            get {
                return this.lastModifiedDateFieldSpecified;
            }
            set {
                this.lastModifiedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public contractor contractor {
            get {
                return this.contractorField;
            }
            set {
                this.contractorField = value;
            }
        }
        
        /// <remarks/>
        public hierarchyType hierarchyType {
            get {
                return this.hierarchyTypeField;
            }
            set {
                this.hierarchyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contractType")]
        public string contractType1 {
            get {
                return this.contractType1Field;
            }
            set {
                this.contractType1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public contractStatusType contractStatus {
            get {
                return this.contractStatusField;
            }
            set {
                this.contractStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> contractValue {
            get {
                return this.contractValueField;
            }
            set {
                this.contractValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractValueSpecified {
            get {
                return this.contractValueFieldSpecified;
            }
            set {
                this.contractValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string parentContractNumber {
            get {
                return this.parentContractNumberField;
            }
            set {
                this.parentContractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> parentContractVersionNumber {
            get {
                return this.parentContractVersionNumberField;
            }
            set {
                this.parentContractVersionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parentContractVersionNumberSpecified {
            get {
                return this.parentContractVersionNumberFieldSpecified;
            }
            set {
                this.parentContractVersionNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string amendmentType {
            get {
                return this.amendmentTypeField;
            }
            set {
                this.amendmentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class fundingType {
        
        private string fundingTypeCodeField;
        
        private string fundingTypeNameField;
        
        /// <remarks/>
        public string fundingTypeCode {
            get {
                return this.fundingTypeCodeField;
            }
            set {
                this.fundingTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string fundingTypeName {
            get {
                return this.fundingTypeNameField;
            }
            set {
                this.fundingTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class contractStatusType {
        
        private contractStatusTypeStatus statusField;
        
        private contractStatusTypeParentStatus parentStatusField;
        
        /// <remarks/>
        public contractStatusTypeStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public contractStatusTypeParentStatus parentStatus {
            get {
                return this.parentStatusField;
            }
            set {
                this.parentStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public enum contractStatusTypeStatus {
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Unassigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Review")]
        InReview,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Awaiting Internal Approval")]
        AwaitingInternalApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Internally Approved")]
        InternallyApproved,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Published To Provider")]
        PublishedToProvider,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Withdrawn By Provider")]
        WithdrawnByProvider,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Withdrawn By Agency")]
        WithdrawnByAgency,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Auto-Withdrawn")]
        AutoWithdrawn,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Under Termination")]
        UnderTermination,
        
        /// <remarks/>
        Terminated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public enum contractStatusTypeParentStatus {
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Withdrawn,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        Replaced,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class TerminationContractAttrsCT {
        
        private System.Nullable<System.DateTime> terminationDateField;
        
        private bool terminationDateFieldSpecified;
        
        private ReasonForTerminationType reasonForTerminationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> terminationDate {
            get {
                return this.terminationDateField;
            }
            set {
                this.terminationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool terminationDateSpecified {
            get {
                return this.terminationDateFieldSpecified;
            }
            set {
                this.terminationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ReasonForTerminationType ReasonForTermination {
            get {
                return this.reasonForTerminationField;
            }
            set {
                this.reasonForTerminationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public enum ReasonForTerminationType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Notice from Provider")]
        NoticefromProvider,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Notice from Agency")]
        NoticefromAgency,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Provider in Liquidation")]
        ProviderinLiquidation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Provider Change")]
        ProviderChange,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class TerminationAllocationAttrsCT {
        
        private System.Nullable<System.DateTime> terminationDateField;
        
        private bool terminationDateFieldSpecified;
        
        private System.Nullable<System.DateTime> stopNewStartsFromDateField;
        
        private bool stopNewStartsFromDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> terminationDate {
            get {
                return this.terminationDateField;
            }
            set {
                this.terminationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool terminationDateSpecified {
            get {
                return this.terminationDateFieldSpecified;
            }
            set {
                this.terminationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> stopNewStartsFromDate {
            get {
                return this.stopNewStartsFromDateField;
            }
            set {
                this.stopNewStartsFromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stopNewStartsFromDateSpecified {
            get {
                return this.stopNewStartsFromDateFieldSpecified;
            }
            set {
                this.stopNewStartsFromDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class allocationStatusType {
        
        private allocationStatusTypeStatus statusField;
        
        /// <remarks/>
        public allocationStatusTypeStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public enum allocationStatusTypeStatus {
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Withdrawn,
        
        /// <remarks/>
        Replaced,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Under Termination")]
        UnderTermination,
        
        /// <remarks/>
        Terminated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class contractor {
        
        private string organisationIdentifierField;
        
        private int ukprnField;
        
        private bool ukprnFieldSpecified;
        
        private string legalNameField;
        
        private string registeredCompanyNumberField;
        
        private int organisationAddressIdentifierField;
        
        private bool organisationAddressIdentifierFieldSpecified;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string addressLine4Field;
        
        private string addressLine5Field;
        
        private string townField;
        
        private string postcodeField;
        
        /// <remarks/>
        public string organisationIdentifier {
            get {
                return this.organisationIdentifierField;
            }
            set {
                this.organisationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int ukprn {
            get {
                return this.ukprnField;
            }
            set {
                this.ukprnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ukprnSpecified {
            get {
                return this.ukprnFieldSpecified;
            }
            set {
                this.ukprnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string legalName {
            get {
                return this.legalNameField;
            }
            set {
                this.legalNameField = value;
            }
        }
        
        /// <remarks/>
        public string registeredCompanyNumber {
            get {
                return this.registeredCompanyNumberField;
            }
            set {
                this.registeredCompanyNumberField = value;
            }
        }
        
        /// <remarks/>
        public int organisationAddressIdentifier {
            get {
                return this.organisationAddressIdentifierField;
            }
            set {
                this.organisationAddressIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool organisationAddressIdentifierSpecified {
            get {
                return this.organisationAddressIdentifierFieldSpecified;
            }
            set {
                this.organisationAddressIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string addressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string addressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string addressLine4 {
            get {
                return this.addressLine4Field;
            }
            set {
                this.addressLine4Field = value;
            }
        }
        
        /// <remarks/>
        public string addressLine5 {
            get {
                return this.addressLine5Field;
            }
            set {
                this.addressLine5Field = value;
            }
        }
        
        /// <remarks/>
        public string town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class allocationOrganisationRelationships {
        
        private string contractAllocationNumberField;
        
        private allocationOrganisationRelationshipType relationshipTypeField;
        
        private contractor organisationField;
        
        /// <remarks/>
        public string contractAllocationNumber {
            get {
                return this.contractAllocationNumberField;
            }
            set {
                this.contractAllocationNumberField = value;
            }
        }
        
        /// <remarks/>
        public allocationOrganisationRelationshipType RelationshipType {
            get {
                return this.relationshipTypeField;
            }
            set {
                this.relationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        public contractor Organisation {
            get {
                return this.organisationField;
            }
            set {
                this.organisationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public enum allocationOrganisationRelationshipType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DELIVERY ORGANISATION")]
        DELIVERYORGANISATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class ProcurementAttrsCT {
        
        private string tenderSpecReferenceField;
        
        private string tenderSpecTitleField;
        
        private string lotReferenceField;
        
        private string lotSpecificationTitleField;
        
        private string awardReferenceField;
        
        private string activityDescriptionField;
        
        private string investmentPriorityField;
        
        private string lEPCodeField;
        
        private string lEPNameField;
        
        private string regionTypeField;
        
        private string agreementNumberField;
        
        private decimal learningRatePremiumField;
        
        /// <remarks/>
        public string TenderSpecReference {
            get {
                return this.tenderSpecReferenceField;
            }
            set {
                this.tenderSpecReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string TenderSpecTitle {
            get {
                return this.tenderSpecTitleField;
            }
            set {
                this.tenderSpecTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotReference {
            get {
                return this.lotReferenceField;
            }
            set {
                this.lotReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotSpecificationTitle {
            get {
                return this.lotSpecificationTitleField;
            }
            set {
                this.lotSpecificationTitleField = value;
            }
        }
        
        /// <remarks/>
        public string AwardReference {
            get {
                return this.awardReferenceField;
            }
            set {
                this.awardReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityDescription {
            get {
                return this.activityDescriptionField;
            }
            set {
                this.activityDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string InvestmentPriority {
            get {
                return this.investmentPriorityField;
            }
            set {
                this.investmentPriorityField = value;
            }
        }
        
        /// <remarks/>
        public string LEPCode {
            get {
                return this.lEPCodeField;
            }
            set {
                this.lEPCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LEPName {
            get {
                return this.lEPNameField;
            }
            set {
                this.lEPNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegionType {
            get {
                return this.regionTypeField;
            }
            set {
                this.regionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AgreementNumber {
            get {
                return this.agreementNumberField;
            }
            set {
                this.agreementNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal LearningRatePremium {
            get {
                return this.learningRatePremiumField;
            }
            set {
                this.learningRatePremiumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class organisationRelationship {
        
        private organisationRelationshipType organisationRelationshipTypeField;
        
        private int organisationIdentifierField;
        
        /// <remarks/>
        public organisationRelationshipType organisationRelationshipType {
            get {
                return this.organisationRelationshipTypeField;
            }
            set {
                this.organisationRelationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        public int organisationIdentifier {
            get {
                return this.organisationIdentifierField;
            }
            set {
                this.organisationIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public enum organisationRelationshipType {
        
        /// <remarks/>
        LEP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FUNDING ORGANISATION")]
        FUNDINGORGANISATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class deliverableType {
        
        private string fundingStreamCodeField;
        
        private int deliverableCodeField;
        
        private string businessCodeField;
        
        private string deliverableNameField;
        
        /// <remarks/>
        public string fundingStreamCode {
            get {
                return this.fundingStreamCodeField;
            }
            set {
                this.fundingStreamCodeField = value;
            }
        }
        
        /// <remarks/>
        public int deliverableCode {
            get {
                return this.deliverableCodeField;
            }
            set {
                this.deliverableCodeField = value;
            }
        }
        
        /// <remarks/>
        public string businessCode {
            get {
                return this.businessCodeField;
            }
            set {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deliverableName {
            get {
                return this.deliverableNameField;
            }
            set {
                this.deliverableNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class fundingStream {
        
        private string fundingStreamCodeField;
        
        private string fundingStreamNameField;
        
        private string fundingTypeCodeField;
        
        private string fundingStreamShortCodeField;
        
        /// <remarks/>
        public string fundingStreamCode {
            get {
                return this.fundingStreamCodeField;
            }
            set {
                this.fundingStreamCodeField = value;
            }
        }
        
        /// <remarks/>
        public string fundingStreamName {
            get {
                return this.fundingStreamNameField;
            }
            set {
                this.fundingStreamNameField = value;
            }
        }
        
        /// <remarks/>
        public string fundingTypeCode {
            get {
                return this.fundingTypeCodeField;
            }
            set {
                this.fundingTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fundingStreamShortCode {
            get {
                return this.fundingStreamShortCodeField;
            }
            set {
                this.fundingStreamShortCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class periodTypeType {
        
        private periodTypeCodeType periodTypeCodeField;
        
        private periodTypeNameType periodTypeNameField;
        
        /// <remarks/>
        public periodTypeCodeType periodTypeCode {
            get {
                return this.periodTypeCodeField;
            }
            set {
                this.periodTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public periodTypeNameType periodTypeName {
            get {
                return this.periodTypeNameField;
            }
            set {
                this.periodTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public enum periodTypeCodeType {
        
        /// <remarks/>
        AY,
        
        /// <remarks/>
        FY,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CQ,
        
        /// <remarks/>
        ESF,
        
        /// <remarks/>
        EOF,
        
        /// <remarks/>
        EOP,
        
        /// <remarks/>
        LEVY,
        
        /// <remarks/>
        NONLEVY,
        
        /// <remarks/>
        NCS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public enum periodTypeNameType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ACADEMIC YEAR")]
        ACADEMICYEAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FINANCIAL YEAR")]
        FINANCIALYEAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CALENDAR YEAR")]
        CALENDARYEAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CALENDAR MONTH")]
        CALENDARMONTH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CALENDAR QUARTER")]
        CALENDARQUARTER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("EUROPEAN SOCIAL FUND")]
        EUROPEANSOCIALFUND,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("EMPLOYER OWNERSHIP FUND")]
        EMPLOYEROWNERSHIPFUND,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("EMPLOYER OWNERSHIP PILOT")]
        EMPLOYEROWNERSHIPPILOT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("APPRENTICESHIP LEVY")]
        APPRENTICESHIPLEVY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NON-LEVY APPRENTICESHIPS")]
        NONLEVYAPPRENTICESHIPS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NATIONAL CAREERS SERVICE")]
        NATIONALCAREERSSERVICE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public partial class period {
        
        private periodTypeType periodTypeField;
        
        private fundingStreamPeriodsFundingStreamPeriod[] fundingStreamPeriodsField;
        
        private string period1Field;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        public periodTypeType periodType {
            get {
                return this.periodTypeField;
            }
            set {
                this.periodTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fundingStreamPeriod", IsNullable=false)]
        public fundingStreamPeriodsFundingStreamPeriod[] fundingStreamPeriods {
            get {
                return this.fundingStreamPeriodsField;
            }
            set {
                this.fundingStreamPeriodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("period")]
        public string period1 {
            get {
                return this.period1Field;
            }
            set {
                this.period1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public partial class fundingStreamPeriodsFundingStreamPeriod {
        
        private string fundingStreamPeriodCodeField;
        
        /// <remarks/>
        public string fundingStreamPeriodCode {
            get {
                return this.fundingStreamPeriodCodeField;
            }
            set {
                this.fundingStreamPeriodCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public partial class contractAllocationsContractAllocation {
        
        private contractAllocationsContractAllocation[] contractAllocationsField;
        
        private period periodField;
        
        private fundingStream fundingStreamField;
        
        private contractDeliverablesTypeContractDeliverable[] contractDeliverablesField;
        
        private string contractAllocationNumberField;
        
        private string descriptionField;
        
        private contractAllocationsContractAllocationHierarchyType hierarchyTypeField;
        
        private string fundingStreamPeriodCodeField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private decimal maximumContractValueField;
        
        private bool maximumContractValueFieldSpecified;
        
        private string reasonForAmendmentField;
        
        private string uopCodeField;
        
        private ProcurementAttrsCT procurementAttrsField;
        
        private allocationOrganisationRelationships allocationOrganisationRelationshipsField;
        
        private allocationStatusType allocationStatusField;
        
        private System.Nullable<System.DateTime> statusLastUpdatedDateField;
        
        private bool statusLastUpdatedDateFieldSpecified;
        
        private TerminationAllocationAttrsCT allocationTerminationAttrsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contractAllocation", IsNullable=false)]
        public contractAllocationsContractAllocation[] contractAllocations {
            get {
                return this.contractAllocationsField;
            }
            set {
                this.contractAllocationsField = value;
            }
        }
        
        /// <remarks/>
        public period period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        public fundingStream fundingStream {
            get {
                return this.fundingStreamField;
            }
            set {
                this.fundingStreamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contractDeliverable", IsNullable=false)]
        public contractDeliverablesTypeContractDeliverable[] contractDeliverables {
            get {
                return this.contractDeliverablesField;
            }
            set {
                this.contractDeliverablesField = value;
            }
        }
        
        /// <remarks/>
        public string contractAllocationNumber {
            get {
                return this.contractAllocationNumberField;
            }
            set {
                this.contractAllocationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public contractAllocationsContractAllocationHierarchyType hierarchyType {
            get {
                return this.hierarchyTypeField;
            }
            set {
                this.hierarchyTypeField = value;
            }
        }
        
        /// <remarks/>
        public string fundingStreamPeriodCode {
            get {
                return this.fundingStreamPeriodCodeField;
            }
            set {
                this.fundingStreamPeriodCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal maximumContractValue {
            get {
                return this.maximumContractValueField;
            }
            set {
                this.maximumContractValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumContractValueSpecified {
            get {
                return this.maximumContractValueFieldSpecified;
            }
            set {
                this.maximumContractValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string reasonForAmendment {
            get {
                return this.reasonForAmendmentField;
            }
            set {
                this.reasonForAmendmentField = value;
            }
        }
        
        /// <remarks/>
        public string uopCode {
            get {
                return this.uopCodeField;
            }
            set {
                this.uopCodeField = value;
            }
        }
        
        /// <remarks/>
        public ProcurementAttrsCT ProcurementAttrs {
            get {
                return this.procurementAttrsField;
            }
            set {
                this.procurementAttrsField = value;
            }
        }
        
        /// <remarks/>
        public allocationOrganisationRelationships allocationOrganisationRelationships {
            get {
                return this.allocationOrganisationRelationshipsField;
            }
            set {
                this.allocationOrganisationRelationshipsField = value;
            }
        }
        
        /// <remarks/>
        public allocationStatusType allocationStatus {
            get {
                return this.allocationStatusField;
            }
            set {
                this.allocationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> StatusLastUpdatedDate {
            get {
                return this.statusLastUpdatedDateField;
            }
            set {
                this.statusLastUpdatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusLastUpdatedDateSpecified {
            get {
                return this.statusLastUpdatedDateFieldSpecified;
            }
            set {
                this.statusLastUpdatedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TerminationAllocationAttrsCT allocationTerminationAttrs {
            get {
                return this.allocationTerminationAttrsField;
            }
            set {
                this.allocationTerminationAttrsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public partial class contractDeliverablesTypeContractDeliverable {
        
        private contractDeliverablesTypeContractDeliverable[][] contractDeliverablesField;
        
        private deliverableType deliverableField;
        
        private contractDeliverablePeriodsTypeContractDeliverablePeriod[] contractDeliverablePeriodsField;
        
        private organisationRelationship[] deliverableOrganisationRelationshipsField;
        
        private string deliverableDescriptionField;
        
        private decimal unitCostField;
        
        private bool unitCostFieldSpecified;
        
        private int plannedVolumeField;
        
        private bool plannedVolumeFieldSpecified;
        
        private decimal plannedValueField;
        
        private bool plannedValueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contractDeliverable", typeof(contractDeliverablesTypeContractDeliverable), IsNullable=false)]
        public contractDeliverablesTypeContractDeliverable[][] contractDeliverables {
            get {
                return this.contractDeliverablesField;
            }
            set {
                this.contractDeliverablesField = value;
            }
        }
        
        /// <remarks/>
        public deliverableType deliverable {
            get {
                return this.deliverableField;
            }
            set {
                this.deliverableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contractDeliverablePeriod", IsNullable=false)]
        public contractDeliverablePeriodsTypeContractDeliverablePeriod[] contractDeliverablePeriods {
            get {
                return this.contractDeliverablePeriodsField;
            }
            set {
                this.contractDeliverablePeriodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("deliverableOrganisationRelationship", IsNullable=false)]
        public organisationRelationship[] deliverableOrganisationRelationships {
            get {
                return this.deliverableOrganisationRelationshipsField;
            }
            set {
                this.deliverableOrganisationRelationshipsField = value;
            }
        }
        
        /// <remarks/>
        public string deliverableDescription {
            get {
                return this.deliverableDescriptionField;
            }
            set {
                this.deliverableDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal unitCost {
            get {
                return this.unitCostField;
            }
            set {
                this.unitCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitCostSpecified {
            get {
                return this.unitCostFieldSpecified;
            }
            set {
                this.unitCostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int plannedVolume {
            get {
                return this.plannedVolumeField;
            }
            set {
                this.plannedVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plannedVolumeSpecified {
            get {
                return this.plannedVolumeFieldSpecified;
            }
            set {
                this.plannedVolumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal plannedValue {
            get {
                return this.plannedValueField;
            }
            set {
                this.plannedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plannedValueSpecified {
            get {
                return this.plannedValueFieldSpecified;
            }
            set {
                this.plannedValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public partial class contractDeliverablePeriodsTypeContractDeliverablePeriod {
        
        private int yearField;
        
        private int periodField;
        
        private periodTypeType periodTypeField;
        
        private decimal unitCostField;
        
        private bool unitCostFieldSpecified;
        
        private int plannedVolumeField;
        
        private bool plannedVolumeFieldSpecified;
        
        private decimal plannedValueField;
        
        private bool plannedValueFieldSpecified;
        
        /// <remarks/>
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public int period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        public periodTypeType periodType {
            get {
                return this.periodTypeField;
            }
            set {
                this.periodTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal unitCost {
            get {
                return this.unitCostField;
            }
            set {
                this.unitCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitCostSpecified {
            get {
                return this.unitCostFieldSpecified;
            }
            set {
                this.unitCostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int plannedVolume {
            get {
                return this.plannedVolumeField;
            }
            set {
                this.plannedVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plannedVolumeSpecified {
            get {
                return this.plannedVolumeFieldSpecified;
            }
            set {
                this.plannedVolumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal plannedValue {
            get {
                return this.plannedValueField;
            }
            set {
                this.plannedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plannedValueSpecified {
            get {
                return this.plannedValueFieldSpecified;
            }
            set {
                this.plannedValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfa:schemas:contract")]
    public enum contractAllocationsContractAllocationHierarchyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CONTRACT ALLOCATION")]
        CONTRACTALLOCATION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SUB ALLOCATION")]
        SUBALLOCATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfa:schemas:contract")]
    public enum hierarchyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MASTER CONTRACT")]
        MASTERCONTRACT,
        
        /// <remarks/>
        CONTRACT,
    }
}
